version: "3.8"

services:
  postgresql:
    build:
      context: ./postgresql
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server-app:
    image: server-app:0.0.1
    ports:
      - "4000:4000"
    environment:
      - POSTGRESQL_HOST=jdbc:postgresql://postgresql:5432/travel_agency_db
      - POSTGRESQL_USERNAME=travel_agency
      - POSTGRESQL_PASSWORD=prolog
    depends_on:
      - postgresql

  phppgadmin:
    image: bitnami/phppgadmin:7.13.0
    ports:
      - "1080:8080"
      - "443:8443"
    environment:
      - POSTGRES_HOST=postgresql
    depends_on:
      - postgresql

volumes:
  postgresql-data:
