# config parameters should be in docker-compose.yml in final release
server:
  port: 4000
  servlet:
    context-path: /server
  error:
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: ${POSTGRESQL_HOST}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

web-config:
  front-app-url: http://localhost:5000
  allowed-method-array: GET, POST, PUT, PATCH, DELETE, OPTIONS

logging:
  level:
    edu.put.serverapp: debug
    org.springframework.security: debug
