# config parameters should be in docker-compose.yml in final release
server:
  port: 5000
  servlet:
    context-path: /server

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/travel_agency_db
    username: travel_agency
    password: prolog
