# config parameters should be in docker-compose.yml in final release
server:
  port: 4000
  servlet:
    context-path: /server
    session:
      cookie:
        secure: false
        http-only: false
  error:
    include-message: always

#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:keystore/travel-agency-key.p12
#    key-store-password: prolog
#    key-alias: travel-agency-key

spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/travel_agency_db
    username: travel_agency
    password: prolog

web-config:
  front-app-url: http://localhost:5000
  allowed-method-array: GET, POST, PUT, PATCH, DELETE, OPTIONS

logging:
  level:
    edu.put.serverapp: debug
    org.springframework.security: debug
