# config parameters should be in docker-compose.yml in final release
server:
  port: 4000
  servlet:
    context-path: /server
  error:
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: ${POSTGRESQL_HOST:jdbc:postgresql://localhost:5432/travel_agency_db}
    username: ${POSTGRESQL_USERNAME:travel_agency}
    password: ${POSTGRESQL_PASSWORD:prolog}

logging:
  level:
    edu.put.serverapp: debug
    org.springframework.security: debug
